### ISSUE TITLE
Exception: The cookies provided by YetAnotherCloudProxy are not valid

### ISSUE THREAD

**Issue by abeloin** [abeloin/Jackett#4]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux

**.Net Runtime**: .Net-Core

**.Net Version**: 3.1

**Jackett Version**: 0.117.1

### Description

Exception in YetAnotherCloudProxySharp

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by YetAnotherCloudProxy are not valid
 ---> System.Exception: Parse error
 ---> YetAnotherCloudProxySharp.Exceptions.YetAnotherCloudProxyException: The cookies provided by YetAnotherCloudProxy are not valid
   at YetAnotherCloudProxySharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 166
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 499
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 512
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1295
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 686
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1629
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 394
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 394
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 663
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 447

Error on 20201208003009 for YGGtorrent.txtYetAnotherCloudProxySharp.Exceptions.YetAnotherCloudProxyException: The cookies provided by YetAnotherCloudProxy are not valid
   at YetAnotherCloudProxySharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 166
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 499
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 512
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1295
```

**Comment by abeloin** [comment]
Seem to be there is a Captcha:


```
INFO REQ-385 Cloudflare detected
DEBUG REQ-385 Waiting for Cloudflare challenge...
DEBUG REQ-385 Validating HTML code...
INFO REQ-385 Successful response in 5.638 s
INFO REQ-385 Captcha detected but no automatic solver is configured.
```

**Comment by NoahCardoza** [comment]
That shouldn't be too hard to solve. I'm thinking I should enable the hcaptcha solver by default since CF now uses it exclusively now.

Thoughts?

**Comment by xfouloux** [comment]
I'm pretty sure it would solve a lot of issue yes !

**Comment by abeloin** [comment]
Have created an issue to have more useful error message than that.

https://github.com/abeloin/YetAnotherCloudProxySharp/issues/1

**Comment by NeZios** [comment]
Hi, I'm having this issue as well.
Hope it will be fix soon ! 🙂

**Comment by abeloin** [comment]
@NoahCardoza Does it work most of the time?

I was thinking of having the possibility of using 2captcha to resolve it but looking at this documentation it seem a little bit more complicated:

https://github.com/scaredos/cfresearch
https://github.com/JimmyLaurent/cloudflare-scraper

**Comment by abeloin** [comment]
Doesn't work anymore
