### ISSUE TITLE
Yggcookie issue

### ISSUE THREAD

**Issue by xfouloux** [abeloin/Jackett#5]
Hey,

Using the tag for cache + cloudproxy you build earlier and cloudproxy latest docker, i can see that jackett use cloudproxy for listing torrents for YGGcookie

Cloudproxy Debug
```
2020-12-10T09:17:32.646Z INFO REQ-9 Incoming request: POST /v1
2020-12-10T09:17:32.648Z INFO REQ-9 Params: {"headers":null,"maxTimeout":60000,"cmd":"request.get","url":"https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"}
2020-12-10T09:17:33.223Z INFO REQ-9 Cloudflare detected
2020-12-10T09:17:37.474Z INFO REQ-9 Successful response in 4.828 s
2020-12-10T09:17:37.474Z INFO REQ-9 Captcha detected but no automatic solver is configured.
```

but then when i try to download a file 

Jackett log
```
2020-12-10 10:20:17.5955 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www2.yggtorrent.si/engine/download_torrent?id=xxxxxxx)
2020-12-10 10:20:17.6845 Debug WebClient(HttpWebClient2): Returning OK => 55 bytes <BINARY>
2020-12-10 10:20:17.6845 Error Vous devez vous connecter pour télécharger un torrent
2020-12-10 10:20:17.6845 Error Error downloading. indexer: yggcookie path: https://www2.yggtorrent.si/engine/download_torrent?id=xxxxxxx
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found 'V' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85
2020-12-10 10:20:17.6845 Info Executing HttpStatusCodeResult, setting HTTP status code 404
2020-12-10 10:20:17.6845 Info Executed action Jackett.Server.Controllers.DownloadController.Download (jackett) in 93.2267ms
2020-12-10 10:20:17.6845 Info Executed endpoint 'Jackett.Server.Controllers.DownloadController.Download (jackett)'
2020-12-10 10:20:17.6845 Info Request finished HTTP/1.1 GET http://xxxxxxxxxxxxxxxxxxxxxxxxxxxx/dl/yggcookie/?jackett_apikey=xxxxxxx&path=Q2ZESjhQTkRsVXg5c2ZGTWpfZkxXdk1meUtweXhoeGhtZkJRdzlxbkgzeVp1cjJqYllTelFIRWtGLXdLTTl4RXJGc0YzNU5vT2xRcndMTXIwX2N6SHNqVnJjM3FmejhvSnVma2hCaWhqaGFmREg4OVRmczBPb05MaHJ3eXFTak9LOENVbXBMbmcxY3hRckNLazNCT19fcEY0emdtNWs1SFV1U1VvaGNsZFNicVZmTEtNTEhZQlIxZWlZUkoyTklwenFYbkNn&file=xxxxxxxxxxxxxxxxxxxxxxxxxxxx - - - 404 0 - 98.4201ms
2020-12-10 10:20:17.6845 Debug Connection id "0HM4SSTL5MHJI" disconnecting.
2020-12-10 10:20:17.6845 Debug Connection id "0HM4SSTL5MHJI" stopped.
2020-12-10 10:20:17.6874 Debug Connection id "0HM4SSTL5MHJI" received FIN.
2020-12-10 10:20:17.6874 Debug Connection id "0HM4SSTL5MHJI" sending FIN because: "The Socket transport's send loop completed gracefully." 
```

we can see that jacket won't use cloudflaresolver to download the file.
and yeah cloudflaresolver logs are empty, so it is not used.

But YGGTorrent indexer, works fine, only the cookie one, I don't really know where the issue lies.

**Comment by abeloin** [comment]
I think your getting this because your cookies have expired.

Ygg returned the following string when you tried to download the file:
`Vous devez vous connecter pour télécharger un torrent`

Cloudproxy is only used to get the cookies when a challenge is detected, after Jackett will connect directly to YGG.

So I would think it should not detect a challenge when using YGGCookies. I'll have to check this to confirm it since I'm using YGGtorrent.

Have you try to use YGGtorrent instead of YGGCookie

Because I added a login check when downloading since 0.117.1 and should be in 0.117.2(which include the cache thing) which should help with expired cookies when using YGGtorrent

**Comment by xfouloux** [comment]
YGGTorrent works fine, only the cookie one give me errors this is weird =)
Might be completely unrelated, and moreover i prefer to use the YGGTorrent over the cookie one, because i don't have to change the cookie input every one in a while.

**Comment by abeloin** [comment]
The user-agent string in the config doesn't seem to be used anywhere, so when generating the cookie :

- Use chrome
- Spoof the user-agent to:

"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" or
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

But still doesn't work properly, will have to check if the cookies are properly sent

**Comment by abeloin** [comment]
@xfouloux  You should try with Jacket v0.17.50 which now include flaresolverr(cloudproxy)

**Comment by xfouloux** [comment]
Yeah sure, i was waiting for the release =)

**Comment by xfouloux** [comment]
indeed, upgrading to latest jackett + flaresolverr/flaresolverr has now fixed the issue
